# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

image:
  repository: ghcr.io/zystem/harbor-vulnerabilities-exporter
  pullPolicy: IfNotPresent
  tag: ""
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
podLabels: {}

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534
  runAsGroup: 65534
  capabilities:
    drop:
      - ALL

existingSecret:
  name: ""
# OR
env:
  EXPORTER_PORT: "9090"
  HARBOR_API_URL: ""
  HARBOR_USERNAME: ""
  HARBOR_PASSWORD: ""
  REFRESH_INTERVAL_SECONDS: "600"
  PROM_LITE_DATA_DIR: "/data"
  INCLUDE_PROJECTS: ""
  EXCLUDE_PROJECTS: ""
  INCLUDE_REPOSITORIES: ""
  EXCLUDE_REPOSITORIES: ""

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /healthz
    port: metrics
readinessProbe:
  httpGet:
    path: /healthz
    port: metrics

nodeSelector: {}
tolerations: []
affinity: {}

podMonitor:
  enabled: true
  labels: {}
  scrapeTimeout: "30s"
  scrapeInterval: "600s"
