{{- if .Values.podMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "harbor-vulnerabilities-exporter.name" . }}
  labels:
{{- include "harbor-vulnerabilities-exporter.labels" . | nindent 4 }}
spec:
  jobLabel: harbor-vulnerabilities-exporter
  selector:
    matchLabels:
{{- include "harbor-vulnerabilities-exporter.labels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.podMonitor.scrapeInterval }}
      scrapeTimeout: {{ .Values.podMonitor.scrapeTimeout }}
{{- end }}
