{{- if not .Values.existingSecret.secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor-vulnerabilities-exporter.fullname" . }}
  labels:
    {{- include "harbor-vulnerabilities-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | toString | quote }}
  {{- end }}
{{- end }}
